const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

async function main() {
  const RPC = process.env.RPC_URL || "http://127.0.0.1:8545";
  const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS;

  if (!CONTRACT_ADDRESS) {
    throw new Error("Set CONTRACT_ADDRESS env var before running this script");
  }

  // Load ABI generated by compilation
  const abiPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "VoiceIt.sol",
    "VoiceIt.json"
  );
  if (!fs.existsSync(abiPath)) {
    throw new Error(`ABI not found at ${abiPath}. Compile contracts first.`);
  }
  const artifact = JSON.parse(fs.readFileSync(abiPath, "utf8"));
  const abi = artifact.abi;

  const provider = new ethers.JsonRpcProvider(RPC);

  const samples = [
    "I faced discrimination at my workplace.",
    "Local community lacks safe drinking water.",
    "I experienced unfair treatment at school.",
  ];

  // Use provider.getSigner(index) for hardhat-unlocked accounts
  for (let i = 0; i < samples.length; i++) {
    const signer = await provider.getSigner(i);
    const addr = await signer.getAddress();
    console.log(`Submitting sample ${i + 1} from ${addr}`);
    const contract = new ethers.Contract(CONTRACT_ADDRESS, abi, signer);
    const tx = await contract.submitReport(samples[i], { gasLimit: 500000 });
    const receipt = await tx.wait();
    console.log(`Submitted tx: ${receipt.transactionHash}`);
  }

  console.log("Seeding complete.");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
