const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

// Hardhat default accounts (from running `npx hardhat node`)
const HARDHAT_ACCOUNTS = [
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb476cbe1dd2b0d7cc2fd61e7c6f0",
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
  "0x6cea9e928e4e9c847efb3b113f3e2eab740e53f7f82efb8d00674e6457ec80a2",
];

async function main() {
  const RPC = process.env.RPC_URL || "http://127.0.0.1:8545";
  const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS;
  if (!CONTRACT_ADDRESS) {
    throw new Error("Set CONTRACT_ADDRESS env var before running this script");
  }

  // Load ABI generated by compilation
  const abiPath = path.join(__dirname, "..", "artifacts", "contracts", "VoiceIt.sol", "VoiceIt.json");
  if (!fs.existsSync(abiPath)) {
    throw new Error(`ABI not found at ${abiPath}. Compile contracts first.`);
  }
  const artifact = JSON.parse(fs.readFileSync(abiPath, "utf8"));
  const abi = artifact.abi;

  const provider = new ethers.JsonRpcProvider(RPC);

  // Create signers from hardcoded Hardhat default private keys
  const signers = HARDHAT_ACCOUNTS.map((pk) => new ethers.Wallet(pk, provider));

  const samples = [
    "I faced discrimination at my workplace.",
    "Local community lacks safe drinking water.",
    "I experienced unfair treatment at school.",
  ];

  for (let i = 0; i < samples.length; i++) {
    const signer = signers[i % signers.length];
    console.log(`Submitting sample ${i + 1} from signer index ${i % signers.length}`);
    const contract = new ethers.Contract(CONTRACT_ADDRESS, abi, signer);
    const tx = await contract.submitReport(samples[i], { gasLimit: 500000 });
    const receipt = await tx.wait();
    console.log(`Submitted tx: ${receipt.transactionHash}`);
  }

  console.log("Seeding complete (simple script).");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
